general.import = ["~/.config/alacritty/colors.toml"]

[font]
size = 11.0

[font.bold]
family = "Caskaydia Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Caskaydia Mono Nerd Font"
style = "Regular"

[window]
dimensions = { columns = 60, lines = 25}
blur = true
opacity = 0.90

