
[font]
size = 10.0

[font.bold]
family = "Freemono"
style = "Bold"

[font.bold_italic]
family = "Freemono"
style = "Bold Italic"

[font.italic]
family = "Freemono"
style = "Italic"

[font.normal]
family = "Freemono"
style = "Regular"

[colors.primary]
foreground = "#ffffff"
background = "#333333"

[window]
dimensions = { columns = 60, lines = 25}
blur = true
opacity = 0.90

