#!/bin/bash
[global]
    frame_color = "#f57e1a"
[urgency_low]
    background = "#0f0f0fCC"
    foreground = "#ffffff"
[urgency_normal]
    background = "#0f0f0fCC"
    foreground = "#ffffff"
[urgency_critical]
    background = "#0f0f0fCC"
    foreground = "#ffffff"
    frame_color = "#900000"
