#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width	3
bspc config window_gap		5
bspc config top_padding		3
bspc config bottom_padding 	3
bspc config left_padding 	3
bspc config right_padding 	3

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color "#7d7d7d"
	bspc config focused_border_color "#1793d1"
	bspc config focus_follows_pointer true

	#bspc rule -a Gimp desktop="^8" state=floating follow=on
#bspc rule -a Chromium desktop="^2"
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#AutoStart
xsetroot -cursor_name left_ptr &
nitrogen --restore &
#xfce4-power-manager &
#killall volumeicon && volumeicon &
blueman-applet &
nm-applet &
/usr/bin/dunst &
/usr/bin/polkit-gnome/polkit-gnome-authentucation-agent-1 &
$HOME/.config/polybar/polybar.sh &
picom &
