#! /bin/sh

source "$HOME/.config/bspwm/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width	2
bspc config window_gap		10
bspc config top_padding		-7
bspc config bottom_padding 	-7
bspc config left_padding 	-7
bspc config right_padding 	-7

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "$base03"
bspc config focused_border_color "$base00"
bspc config focus_follows_pointer true

# Define as cores das bordas
#bspc config focused_border_color "#88C0D0" # Nord: Polar Night Frost (azul claro)
#bspc config normal_border_color "#4C566A"  # Nord: Polar Night (cinza escuro)
#bspc config presel_border_color "#A3BE8C"  # Nord: Frost Green (verde)
#bspc config active_border_color "#BF616A"  # Nord: Aurora Red (vermelho)

#bspc rule -a Gimp desktop="^8" state=floating follow=on
#bspc rule -a Chromium desktop="^2"
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a "stream-overlay" border=off

#AutoStart
xsetroot -cursor_name left_ptr &
#nitrogen --restore &
#xfce4-power-manager &
#killall volumeicon && volumeicon &
blueman-applet &
nm-applet &
/usr/bin/dunst &
/usr/bin/polkit-gnome/polkit-gnome-authentucation-agent-1 &
/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg &
feh --bg-scale ~/.config/wallpapers/$wallpaper &
$HOME/.config/polybar/polybar.sh &
picom &
xset -b &
kdeconnect-indicator &
syncthing --no-browser &
