#!/bin/bash

# --- VARIABLES ---
# Define variables for paths and themes to make the script cleaner and easier to modify.
readonly GTK2_DIR="$HOME/.config/gtk-2.0"
readonly GTK3_DIR="$HOME/.config/gtk-3.0"
readonly GTK4_DIR="$HOME/.config/gtk-4.0"
readonly NWG_LOOK_GSETTINGS="$HOME/.local/share/nwg-look/gsettings"
readonly LIGHTDM_GTK_GREETER_CONF="/etc/lightdm/lightdm-gtk-greeter.conf"

# --- THEME SETTINGS ---
# Define themes for light and dark modes.
declare -A LIGHT_THEME
LIGHT_THEME[gtk]="Breeze"
LIGHT_THEME[icon]="Papirus-Light"
LIGHT_THEME[cursor]="capitaine-cursors-light"
LIGHT_THEME[greeter_theme]="Breeze"
LIGHT_THEME[greeter_icon]="Papirus-Light"
LIGHT_THEME[greeter_cursor]="capitaine-cursors-light"
LIGHT_THEME[notification]="Light"

declare -A DARK_THEME
DARK_THEME[gtk]="Breeze-Dark"
DARK_THEME[icon]="Papirus-Dark"
DARK_THEME[cursor]="capitaine-cursors"
DARK_THEME[greeter_theme]="Breeze-Dark"
DARK_THEME[greeter_icon]="Papirus-Dark"
DARK_THEME[greeter_cursor]="capitaine-cursors"
DARK_THEME[notification]="Dark"

# --- FUNCTIONS ---
# Function to apply the selected theme.
apply_theme() {
    local -n theme=$1 # Use a nameref for passing the theme array.
    local gtk_theme="${theme[gtk]}"
    local icon_theme="${theme[icon]}"
    local cursor_theme="${theme[cursor]}"
    local greeter_theme="${theme[greeter_theme]}"
    local greeter_icon="${theme[greeter_icon]}"
    local greeter_cursor="${theme[greeter_cursor]}"
    local notification_text="${theme[notification]}"

    # GTK settings for nwg-look
    cat <<EOF > "$NWG_LOOK_GSETTINGS"
# Generated by Jhonatanrs
gtk-theme=$gtk_theme
icon-theme=$icon_theme
font-name=FreeMono 10
cursor-theme=$cursor_theme
cursor-size=24
toolbar-style=both-horiz
toolbar-icons-size=large
font-hinting=medium
font-antialiasing=grayscale
font-rgba-order=rgb
text-scaling-factor=1.0
color-scheme=default
event-sounds=true
input-feedback-sounds=true
EOF

    # LightDM GTK Greeter settings
    cat <<EOF > "$LIGHTDM_GTK_GREETER_CONF"
[greeter]
theme-name = $greeter_theme
icon-theme-name = $greeter_icon
cursor-theme-name = $greeter_cursor
indicators = ~session;~spacer;~clock;~spacer;~power
background = /usr/share/backgrounds/main.png
font-name = FreeMono 10
EOF

    # Apply settings via nwg-look and sync GTK config files
    nwg-look -a
    nwg-look -x
    cp "$GTK3_DIR/settings.ini" "$GTK2_DIR/settings.ini"
    cp "$GTK3_DIR/settings.ini" "$GTK4_DIR/settings.ini"

    # Specific desktop environment actions
    case "$DESKTOP_SESSION" in
        "hyprland")
            hyprctl setcursor "$cursor_theme" 24
            ;;
        "bspwm")
            bspc wm -r # Reload bspwm configuration
            ;;
    esac

    # Send a desktop notification
    dunstify -t 1000 --hints int:transient:1 "Theme Mode" "$notification_text" --icon=preferences-desktop-theme
}

# --- MAIN LOGIC ---
# Create directories if they don't exist.
mkdir -p "$GTK2_DIR" "$GTK3_DIR" "$GTK4_DIR"

# Check the current theme and toggle it.
current_theme=$(grep "gtk-theme" "$NWG_LOOK_GSETTINGS" | cut -d '=' -f 2)

case "$current_theme" in
    "Breeze-Dark")
        apply_theme LIGHT_THEME
        ;;
    *) # Default to dark mode if current theme is not explicitly light.
        apply_theme DARK_THEME
        ;;
esac
